name: jayesh_flutter
description: "A Flutter portfolio website with dynamic content from Firebase Remote Config."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  acyclic_steps: ^0.11.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.3.1
  firebase_core: ^2.0.0
  firebase_remote_config: ^4.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/jayesh_ghadge_resume.pdf